module PingMeMaybe
    module Constants
        CRONUT_API_TOKEN_HEADER = 'X-CRONUT-API-TOKEN'
        CRONUT_HOST = ENV["CRONUT_HOST"]
        CRONUT_API_TOKEN = ENV['CRONUT_API_TOKEN']
        CRONUT_PUBLIC_KEY = ENV['CRONUT_PUBLIC_KEY']
    end
end